<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Facility;
use App\Models\User;

class FacilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Znajdź admina jako właściciela placówek
        $admin = User::where('email', 'admin@oaza.pl')->first();
        if (!$admin) {
            $admin = User::first();
        }

        $facilities = [
            [
                'name' => 'Katarzyna Andrys',
                'address' => 'Poznań (Dialogownia)',
                'city' => 'Poznań',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dialogownia.com/',
                'description' => 'Podejście terapeutyczne: systemowe, SWR.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Joanna Barbarewicz',
                'address' => 'Gdynia, Warszawa',
                'city' => 'Gdynia',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://przystanekempatia.pl/portfolio-item/joanna-barbarewicz-psycholog-psychoterapeuta/',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Marta Baron',
                'address' => 'Warszawa (Ko-relacje)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://www.ko-relacje.pl/zespol/marta-baron',
                'description' => 'Podejście terapeutyczne: Gestalt.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Beata Błaszyk',
                'address' => 'Bydgoszcz',
                'city' => 'Bydgoszcz',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychoterapia-za.pl/index.php/o-mnie/',
                'description' => 'Podejście terapeutyczne: ericksonowskie.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Alicja Bogaczyk',
                'address' => 'Poznań (Centrum Wspierania Relacji)',
                'city' => 'Poznań',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://wspieranierelacji.pl/',
                'description' => 'Podejście terapeutyczne: TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Kinga Bogdańska',
                'address' => 'Wrocław (Ginamedica)',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://ginemedica.pl/lekarz/kinga-bogdanska/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Katarzyna Borowiec-Mańkowska',
                'address' => 'Bytom (TIPI)',
                'city' => 'Bytom',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/katarzyna-borowiec-mankowska/psycholog-psychoterapeuta/zabrze',
                'description' => 'Podejście terapeutyczne: systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Aleksanra Brzezińska',
                'address' => 'Warszawa (Centrum Psychoterapii i Diagnozy)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.centrumpid.com/aleksandra-brzezinska',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Joanna Burgiełł',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://joannaburgiell.wixsite.com/psychoterapia',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Monika Całka',
                'address' => 'Warszawa (Integra)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychopracownia-integra.pl/zespol/#monikaa-calka',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Maja Chaudhuri',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/maja-chaudhuri/psycholog-seksuolog-psychoterapeuta/warszawa?fbclid=IwAR3-VDtwgK1Z91q1OxkoJTmSEVd6TOZhW6xC4sdGqsSNgDZ-U_InZilmsNc',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Paula Chibowska',
                'address' => 'Gdańsk',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/paula-chibowska/psychoterapeuta-psycholog/gdansk',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Patrycja Cichanowska-Hołojda',
                'address' => 'Wałbrzych',
                'city' => 'Wałbrzych',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://pleso.me/pl/therapists?psychologist_id=6ad2f516-f039-3d9f-8e6c-e349f59cf734&booking-widget-step=service_and_calendar_selection',
                'description' => 'Podejście terapeutyczne: integratywne, systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Maria Czarnecka',
                'address' => 'Warszawa (Bliskie miejsce)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://bliskiemiejsce.pl/maria-czarnecka/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne, systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Emilia Czartoryska',
                'address' => 'Gdańsk (HarmonJa)',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.harmonja.pl/zespol/',
                'description' => 'Podejście terapeutyczne: DBT, Gestalt.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Monika Czerepak',
                'address' => 'Wrocław (MedTerapeutica)',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://medterapeutica.pl/mc/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne, systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Eliza Czerka-Fortuna',
                'address' => 'Gdańsk, Gdynia',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/eliza-czerka-fortuna/psycholog-psychoterapeuta/gdansk',
                'description' => 'Podejście terapeutyczne: systemowe, CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Malik Czernek',
                'address' => 'Bielsko-Biała',
                'city' => 'Bielsko-Biała',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://psychologbielsko.eu/kadra/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Urszula Czyżowicz',
                'address' => 'Bygdoszcz',
                'city' => 'Bygdoszcz',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/urszula-czyzowicz/psycholog-psychoterapeuta/bydgoszcz',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Dębska',
                'address' => 'Wrocław (OdNowa)',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://www.psychologodnowa.pl/pl/o-nas/2-uncategorised/64-malgorzata-debska',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Ewa Dobiała',
                'address' => 'Leszno',
                'city' => 'Leszno',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://edobiala.igabinet.pl/g1336221324pol-O-mnie.html',
                'description' => 'Podejście terapeutyczne: TPP, ericksonowskie.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Dorota Dolecka-Semeniuk',
                'address' => 'Lublin',
                'city' => 'Lublin',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/dorota-dolecka/psycholog-psychoterapeuta/lublin',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Marta Dora',
                'address' => 'Pracownia Zasoby (Warszawa), Centrum Terapii Synteza (Kraków)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://pracowniazasoby.pl/',
                'description' => 'Podejście terapeutyczne: systemowo-psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Joanna Drążkiewicz',
                'address' => 'Warszawa (Dialog)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychiatrzy.warszawa.pl/specjalisci/joanna-drazkiewicz',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Katarzyna Dułak',
                'address' => 'Gdańsk, Sopot (Mental Path)',
                'city' => 'Mental Path',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://www.katarzynadulak.pl/',
                'description' => 'Podejście terapeutyczne: Gestalt.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Karolina Dyrda',
                'address' => 'Warszawa (Psychomedic)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychomedic.pl/dt_portfolios/mgr-karolina-dyrda-psycholog-psychoterapeuta-dzieci-i-doroslych-cbt/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Katarzyna Dzwonnik',
                'address' => 'Wrocław',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychologowie-dla-spoleczenstwa.pl/zespol/kasia-dzwonnik',
                'description' => 'Podejście terapeutyczne: Gestalt, systemowe, par, rodzin.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magdalena Flaga-Łuczkiewicz',
                'address' => 'Warszawa (Dialog)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychiatrzy.warszawa.pl/specjalisci/magdalena-flaga-luczkiewicz/',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Tomasz Folusz',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://psycho-terapeuta.warszawa.pl/poznawczo-behawioralny/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Izabela Fornalik',
                'address' => 'Warszawa (Klinika Terapii Poznawczo-Behawioralnej Uniwersytetu SWPS)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://klinika1.swps.pl/index.php',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Patrycja Frania',
                'address' => 'Wrocław (SISU)',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://patrycjafrania.pl/',
                'description' => 'Podejście terapeutyczne: TSR, TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Maria Gaj',
                'address' => 'Łódź (Psychomedic)',
                'city' => 'Łódź',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychomedic.pl/dt_portfolios/mgr-maria-gaj-psycholog-psychoterapeuta-lodz/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Zuzanna Gawor-Kotkowska',
                'address' => 'Warszawa (Neuroverse)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.neuroverse.com.pl/czlonkowie-zespolu/zuzanna',
                'description' => 'Podejście terapeutyczne: różne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Joanna Gieldarska',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://joannagieldarska.pl/pl/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Gołębiewska',
                'address' => 'Poradnia CBT (Gdynia)',
                'city' => 'Gdynia',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/malgorzata-golebiewska-2/psychoterapeuta/gdynia',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Zuzanna Gucwa-Mozolewska',
                'address' => 'Kraków (Vadimed)',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.vadimed.com.pl/dla-pacjenta/godziny-przyjec',
                'description' => 'Podejście terapeutyczne: CBT, psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Michał T. Handzel',
                'address' => 'Indywidualne Wsparcie Terapeutyczne (online)',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.facebook.com/IWTspektrumautyzmu',
                'description' => 'Podejście terapeutyczne: różne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Monika Hołub',
                'address' => 'Warszawa, Żyrardów',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://dobry-psycholog.com/o-mnie',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Marek Husak',
                'address' => 'Warszawa (Cogito)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://savant.org.pl/o-nas/',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Katarzyna Kalinowska',
                'address' => 'Mindhealth (Białystok)',
                'city' => 'Mindhealth',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://mindhealth.pl/specjalisci/mgr-katarzyna-kalinowska',
                'description' => 'Podejście terapeutyczne: systemowe, psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Patrycja Kloza',
                'address' => 'Katowice',
                'city' => 'Katowice',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.pracowniapsychoedukacji.com.pl/',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Elwira Korycka',
                'address' => 'Warszawa (AdAlta)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.adalta.com.pl/elwira-korycka',
                'description' => 'Podejście terapeutyczne: schematów, CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Kornelia Krajowska-Kukieł',
                'address' => 'Synapsis, Centrum Diagnozy i Pomocy Psych. (Warszawa)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychologursus.com.pl/o-nas/nasi-specjalisci/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne, systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Anita Krakowiak',
                'address' => 'online tylko',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://epsycholodzy.pl/blog/psychoterapia-online/psycholog/anita-krakowiak/',
                'description' => 'Podejście terapeutyczne: systemowe, psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Aleksandra Kraszczyńska',
                'address' => 'online tylko',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.terapiatraumy.online/',
                'description' => 'Podejście terapeutyczne: EMDR, CBT, systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magdalena Krukowska-Sidorczuk',
                'address' => 'Warszawa (Luxmed)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://harmonia.luxmed.pl/specjalista/krukowska-sidorczuk-magdalena/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magdalena Krzyżosiak',
                'address' => 'Warszawa (Preludium)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://poradniapreludium.pl/nasz-zespol/magdalena-krzyzosiak/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Justyna Kula-Lic',
                'address' => 'Leżajsk',
                'city' => 'Leżajsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.spzoz-lezajsk.pl/?c=mdTresc-cmPokaz-269',
                'description' => 'Psychoterapia i wsparcie terapeutyczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Kumięga',
                'address' => 'Wrocław (Ginemedica)',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://ginemedica.pl/lekarz/malgorzata-kumiega/',
                'description' => 'Podejście terapeutyczne: systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Karolina Kuźnicka-Przerywacz',
                'address' => 'Kraków (Przyjazna terapia)',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.przyjaznaterapia.pl/karolina_ku%C5%BAnicka_przerywacz-106982-blog.html',
                'description' => 'Podejście terapeutyczne: psychodynamiczne, systemowe, CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Anna Kwiatkowska-Ożegowska',
                'address' => 'Swarzędz, Poznań',
                'city' => 'Swarzędz',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://kwiatkowska-psycholog.pl/omnie.html',
                'description' => 'Psychoterapia i wsparcie terapeutyczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Maja Lasota',
                'address' => 'Ginemedica (Wrocław)',
                'city' => 'Ginemedica',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://ginemedica.pl/lekarz/maja-lasota/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Anna Lenek',
                'address' => 'Gliwice (Wellbee, SELF, PTIMA)',
                'city' => 'Gliwice',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://wellbee.pl/nasi-specjalisci/anna-lenek',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Kamil Dante Lucci',
                'address' => 'Warszawa (Dialog)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychiatrzy.warszawa.pl/specjalisci/kamil-dante-lucci/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Aleksandra Magda',
                'address' => 'Kraków (Mind Works)',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://terapia-cbt.pl/o-nas/aleksandra-magda/',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Karolina Magierek',
                'address' => 'Wejherowo, Gdynia',
                'city' => 'Wejherowo',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/karolina-magierek/psycholog-psychoterapeuta-seksuolog/wejherowo',
                'description' => 'Podejście terapeutyczne: systemowe, EMDR.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Mańko-Marcysiak',
                'address' => 'Bydgoszcz',
                'city' => 'Bydgoszcz',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://www.centrum-pomoc.bydgoszcz.pl/kadra/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Cezary Markowski',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://cpp.pl/team/cezary-markowski/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Agnieksza Mateja',
                'address' => 'Tychy',
                'city' => 'Tychy',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://pracowniapsychologicznamateja.pl/',
                'description' => 'Psychoterapia i wsparcie terapeutyczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Przemysław Matuszyński',
                'address' => 'Gniezno (Matiam PM)',
                'city' => 'Gniezno',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.matiam.pl/o-nas',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magdalena Mętkowska-Walewska',
                'address' => 'Gdańsk',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://metkowska-walewska.pl/',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Joanna Mikołajczyk',
                'address' => 'Poznań (Solutio)',
                'city' => 'Poznań',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychologia-solutio.pl/staff/joanna-mikolajczyk-2/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Łukasz Miścicki',
                'address' => 'Warszawa (Dialog)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychiatrzy.warszawa.pl/specjalisci/lukasz-miscicki/',
                'description' => 'Podejście terapeutyczne: humanistyczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Marta Moszoro',
                'address' => 'Warszawa (Centrum Psychoterapii i Diagnozy)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.centrumpid.com/marta-moszoro',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Ewa Mroczek',
                'address' => 'online tylko',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://ewamroczek.pl/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Ilona Mroczkowska',
                'address' => 'Siedlce',
                'city' => 'Siedlce',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.facebook.com/p/Gabinet-Psychoterapii-Tu-i-Teraz-Ilona-Mroczkowska-100057571056343/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne, systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Patrycja Nalazek',
                'address' => 'Warszawa (Relacje)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://osrodekrelacje.com/zespol-psycholodzy-i-terapeuci/',
                'description' => 'Podejście terapeutyczne: CBT, psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Marzena Okapiec',
                'address' => 'Opole',
                'city' => 'Opole',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://gestaltpsychoterapia.com/o-mnie/',
                'description' => 'Podejście terapeutyczne: Gestalt.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Ostrowska',
                'address' => 'Gdańsk (HarmonJa)',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.harmonja.pl/profile/malgorzata-ostrowska/',
                'description' => 'Podejście terapeutyczne: DBT, CBT, psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Palacz',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/malgorzata-palacz-2/psycholog-psychoterapeuta/warszawa',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Aneta Pietrzak',
                'address' => 'Prodeste (Wrocław)',
                'city' => 'Prodeste',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://prodeste.pl/fundacja/ludzie/',
                'description' => 'Podejście terapeutyczne: TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magda Piórkowska',
                'address' => 'Ostoja (Łódź)',
                'city' => 'Ostoja',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.magdapiorkowska.com/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Anna Pyla-Mazur',
                'address' => 'Kraków',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://annapylamazur.pl/O_MNIE',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Urszula Ratajczak',
                'address' => 'online (związana z Prodeste)',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://porozmawiajmyonline.pl/psycholog/mgr-urszula-ratajczak/',
                'description' => 'Podejście terapeutyczne: TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Grażyna Rembelska',
                'address' => 'Warszawa (Intra)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://osrodekintra.pl/team-view/grazyna-rembelska/',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Paulina Roszkowska',
                'address' => 'online tylko',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.audhdroszkowska.pl/',
                'description' => 'Podejście terapeutyczne: TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Agata Sawicka-Bocian',
                'address' => 'Psychomedic (Wrocław)',
                'city' => 'Psychomedic',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychomedic.pl/dt_portfolios/dr-agata-sawicka-bocian-psycholog-diagnosta-wroclaw/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Renata Sikorska',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychomedic.pl/dt_portfolios/mgr-renata-sikorska-diagnosta-calosciowych-zaburzen-rozwojowych-warszawa/',
                'description' => 'Psychoterapia i wsparcie terapeutyczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Aleksandra Sileńska',
                'address' => 'Szczecin',
                'city' => 'Szczecin',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://mojpsycholog.szczecin.pl/o-mnie/',
                'description' => 'Podejście terapeutyczne: systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magdalena Siwek',
                'address' => 'Centrum Dobrej Terapii (Kraków)',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.centrumdobrejterapii.pl/nasi-specjalisci/magdalena-siwek/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Renata Składanek',
                'address' => 'Dialog (Warszawa)',
                'city' => 'Dialog',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychiatrzy.warszawa.pl/specjalisci/renata-skladanek/',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Dorota Stanisławska',
                'address' => 'Multimed (NFZ) lub Centrum Psychoterapii "Terapiatuli" (prywatnie), Kalisz',
                'city' => 'Multimed',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://terapiatuli.pl/zespol/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Adrianna Stawarz',
                'address' => 'Wrocław',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/adrianna-stawarz/psycholog-seksuolog-psychoterapeuta/wroclaw?fbclid=IwAR2esWqvtjsFKKM-80qpCKSe_Lj5cHzE78swPLnRI1WXbWaoKQxQoH4FkOU',
                'description' => 'Podejście terapeutyczne: integratywne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Martyna Stefańska',
                'address' => 'Bezpieczne Miejsce (Warszawa)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.terapiadbt.pl/team/martyna-stefanska/',
                'description' => 'Podejście terapeutyczne: DBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Martyna Stochel-Morek',
                'address' => 'Katowice (Persevere)',
                'city' => 'Katowice',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://persevere.org.pl/martyna-stochel-morek/',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Justyna Sulej',
                'address' => 'Warszawa (Schematy)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://schema-ty.pl/justyna-sulej/',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Agnieszka Szadurska-Prokopiuk',
                'address' => 'online tylko',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://szadurska-prokopiuk.pl/',
                'description' => 'Podejście terapeutyczne: systemowe, ericksonowskie i TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Zuzanna Szal',
                'address' => 'Wrocław',
                'city' => 'Wrocław',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/zuzanna-szal/psycholog-psycholog-dzieciecy-psychoterapeuta/wroclaw',
                'description' => 'Podejście terapeutyczne: Gestalt.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Agnieszka Szczepocka',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/agnieszka-szczepocka/psychoterapeuta-psycholog/warszawa?utm_medium=ppc&utm_source=google&utm_term=%2Bagnieszka+%2Bszczepocka&utm_campaign=SN-Docs-Name-1&hsa_acc=4342853338&hsa_cam=1590756134&hsa_grp=90781596852&hsa_ad=444376752902&hsa_src=g&hsa_tgt=kwd-843648996694&hsa_kw=%2Bagnieszka+%2Bszczepocka&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjwk5ibBhDqARIsACzmgLTv9NMGjEx-CZpMopKTqt7OhTe34ik74mfdkfSMp9FH1Ihs7W1ihdEaAhFfEALw_wcB',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Maria Szczuka',
                'address' => 'Warszawa (Terapeutyczna PoraDnia)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://poraterapii.pl/zespol/maria-szczuka',
                'description' => 'Podejście terapeutyczne: systemowe.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Julia Szymanowska',
                'address' => 'Warszawa (Inter Ego)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://interego.com.pl/zespol/julia-szymanowska/',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Beata Światłowska',
                'address' => 'Warszawa (COtam?)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychoterapiacotam.pl/zespol-specjalistow/beata-swiatlowska/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Oliwia Tran',
                'address' => 'Poznań',
                'city' => 'Poznań',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://oliwiatran.pl/',
                'description' => 'Podejście terapeutyczne: EMDR, CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Wojciech Trzaskowski',
                'address' => 'Warszwa (Inzpiro)',
                'city' => 'Warszwa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.psychoterapeuci.pl/psycholodzy-i-psychoterapeuci/',
                'description' => 'Podejście terapeutyczne: Gestalt.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Kinga Tucholska',
                'address' => 'Kraków (Integralnie.pl)',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'http://integralnie.pl/o-nas',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Beata Tylus',
                'address' => 'Poznań (Przystań, Invimed)',
                'city' => 'Poznań',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/beata-tylus/psychoterapeuta-seksuolog/poznan',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Monika Ulatowska',
                'address' => 'Gdańska, Warszawa',
                'city' => 'Gdańska',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://ppp4.edu.pl/zespol/monika-ulatowska-radzka/',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Monika Urbaniak',
                'address' => 'Krotoszyn, Poznań',
                'city' => 'Krotoszyn',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/monika-urbaniak-2/psycholog-psychoterapeuta/poznan-krotoszyn?fbclid=IwAR3YSxCQp4F-SQ7A6RJtVwb_GqZ7JnNX6ZHgnLOd7M2lCo98xb9Wo4Xe2JA',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Michalina Voss',
                'address' => 'OTPB (Poznań)',
                'city' => 'OTPB',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://otpb.pl/tarapeuci-behawioralni/',
                'description' => 'Podejście terapeutyczne: CBT, ACT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Małgorzata Walęcka',
                'address' => 'Warszawa (Cogito)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://cogitoterapia.pl/?page_id=228&fbclid=IwAR1c_qFihCvAQTH6YZmNsqLvxSD-jSm7cGhOswfh4B6vRDLy4SAmuM8M2C4',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Agnieszka Warszawa',
                'address' => 'online tylko',
                'city' => 'Online',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.facebook.com/IWTspektrumautyzmu',
                'description' => 'Podejście terapeutyczne: TPP, EDMR.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Aleksandra Wierzbicka',
                'address' => 'Warszawa (InterEgo)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://interego.com.pl/zespol/aleksandra-wierzbicka/',
                'description' => 'Podejście terapeutyczne: CBT, schematów.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Dorota Wiszejko-Wierzbicka',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psycholog-seksuolog.waw.pl/dorota-wiszejko-wierzbicka/',
                'description' => 'Podejście terapeutyczne: analiza grupowa.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Anna Maria Wołyniak',
                'address' => 'Warszawa (Kobiecy aspekt)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://kobiecyaspekt.pl/o-mnie,3,pl.html?fbclid=IwAR3wvg7MYbsSbaDTO-8iSqpu4TpkingQ2Xb9yTsUYyhf_ICC1qbR9uQvD0o',
                'description' => 'Podejście terapeutyczne: CBT, EDMR.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Karolina Woźniak',
                'address' => 'Gdańsk, Gdynia',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://www.znanylekarz.pl/karolina-wozniak-3/psychoterapeuta-psycholog/gdansk',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Joanna Zawadzka-Iwanek',
                'address' => 'Warszawa (Psychopercepcje)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychopercepcje.pl/Joanna_Zawadzka.html',
                'description' => 'Podejście terapeutyczne: CBT.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Paulina Zawadzka',
                'address' => 'Warszawa (Artonomia)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://artonomia.org/o-nas/',
                'description' => 'Podejście terapeutyczne: TPP.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Ewa Zawisza-Wilk',
                'address' => 'Centrum Metody Krakowskiej (Kraków)',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://centrummetodykrakowskiej.pl/blog/zespol-aspergera-wywiad-z-dr-ewa-zawisza-wilk/',
                'description' => 'Psychoterapia i wsparcie terapeutyczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Dagmara Zbroch',
                'address' => 'Warszawa (Psychomedic)',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://psychomedic.pl/dt_portfolios/mgr-dagmara-zbroch-psycholog-psychoterapeuta-dzieci-i-mlodziezy/#naglowekart',
                'description' => 'Podejście terapeutyczne: psychodynamiczne.',
                'source' => 'Lista polecana przez Idę Tyminę',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Gabinet Psychoterapii EXPECTA Barbara Molęda-Kusidło',
                'address' => 'Racibórz',
                'city' => 'Racibórz',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: diagnostyka spektrum autyzmu u osób dorosłych oraz psychoterapia dorosłych osób w spektrum autyzmu. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Gabinet Psychoterapii Wzmocnienie',
                'address' => 'Kraków',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: diagnostyka spektrum autyzmu u osób dorosłych oraz psychoterapia dorosłych osób w spektrum autyzmu. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Centrum Diagnozy i Terapii TUiTAM',
                'address' => 'Łódź',
                'city' => 'Łódź',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: diagnostyka spektrum autyzmu u osób dorosłych. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Pomoc Psychologiczno-Pedagogiczna Urszula Strzelczyk-Raduli',
                'address' => 'Kędzierzyn-Koźle',
                'city' => 'Kędzierzyn-Koźle',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: diagnostyka spektrum autyzmu u osób dorosłych. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Katowicki Instytut Psychoterapii Justyna Marquardt',
                'address' => 'Katowice',
                'city' => 'Katowice',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: diagnostyka spektrum autyzmu u osób dorosłych oraz psychoterapia dorosłych osób w spektrum autyzmu. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Magdalena Kubicka Psychoterapia',
                'address' => 'Gdańsk',
                'city' => 'Gdańsk',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: psychoterapia dorosłych osób w spektrum autyzmu. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Psychoterapia Justyna Paprota',
                'address' => 'Warszawa',
                'city' => 'Warszawa',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: psychoterapia dorosłych osób w spektrum autyzmu. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
            [
                'name' => 'Potęga Relacji. Psycholog Natalia Jabłońska',
                'address' => 'Kraków',
                'city' => 'Kraków',
                'province' => null,
                'postal_code' => null,
                'phone' => null,
                'email' => null,
                'website' => 'https://dziewczynywspektrum.pl/spektrum-inkluzywnosci/lista-certyfikowanych-placowek/',
                'description' => 'Obszar działalności: psychoterapia dorosłych osób w spektrum autyzmu. Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum.',
                'source' => 'Certyfikat Spektrum Inkluzywności Fundacji Dziewczyny w Spektrum',
                'verification_status' => 'certified',
                'type' => 'inne',
            ],
        ];

        foreach ($facilities as $facilityData) {
            $facilityData['user_id'] = $admin ? $admin->id : null;
            Facility::create($facilityData);
        }
    }
}
